backend:
  name: github
  repo: theowindow/Encryptid
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title",       name: "title",       widget: "string" }
      - { label: "Date",        name: "date",         widget: "datetime" }
      - { label: "Category",    name: "category",     widget: "select",
          options: ["Cryptids", "Conspiracies", "Phenomena"] }
      - { label: "Standfirst",  name: "standfirst",   widget: "string" }
      - { label: "Body",        name: "body",          widget: "markdown" }
      - { label: "Veracity",    name: "veracity",     widget: "number",
          min: 1, max: 5, value_type: "int" }
      - { label: "Supernature", name: "supernature",  widget: "number",
          min: 1, max: 5, value_type: "int" }
      - { label: "Overall",     name: "overall",      widget: "select",
          options: ["S", "A", "B", "C", "D", "U"] }
